### PR TITLE
Update binary_search.md

### PR DESCRIPTION
**Pull request by ayescythe**

### CODE REVIEW

**Comment by Niveshpai** [comment]
Added C code for Binary Search Algorithm.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
Just add the code for the binary search, entire source code is not needed

**Review by ayescythe — COMMENTED** [review]
Changes made

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
Please implement the algo with an array.

**Review by ayescythe — COMMENTED** [review]
Updated with array and simplified version.

**Comment by ayescythe** [comment]
Haha. A year to merge it. xD

**Pull request merged**
