### PR TITLE
Binary search added

### PR DESCRIPTION
**Pull request by manoloesparta**

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
Please read contribution guide first

**Comment by manoloesparta** [comment]
@ayan-biswas0412 Updated! :)

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
we don't need the extra file like `docs/searching/binary_search/python.py`

**Comment by manoloesparta** [comment]
@ayan-biswas0412 forgot to remove directory, my bad. Now it's ready.

**Review by ayan-biswas0412 — APPROVED** [review]
Nice work @manoloesparta 🎉

**Pull request merged**
